export const DASHBOARD_MUSCLES = [
  "chest",
  "shoulders",
  "biceps",
  "triceps",
  "forearms",
  "abdominals",
  "quadriceps",
  "calves",
  "traps",
  "lats",
  "glutes",
  "hamstrings",
  "upper back",
  "lower back",
];